"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.preloadResources = exports.preloadResource = exports.isResourcePreloaded = exports.getPreloadStats = exports.getPreloadedResource = exports.clearPreloadCache = exports.registerResourceLoader = exports.loadSVGResource = exports.setDefaultFont = exports.registerPattern = exports.registerPalette = exports.registerFont = exports.getPaletteColor = exports.getPalette = exports.getFonts = exports.getFont = exports.renderSVG = exports.jsxs = exports.jsxDEV = exports.jsx = exports.getElementsBounds = exports.getElementBounds = exports.getCombinedBounds = exports.createLayout = exports.createFragment = exports.cloneElement = exports.Text = exports.Rect = exports.Polygon = exports.Path = exports.Group = exports.Fragment = exports.Ellipse = exports.Defs = exports.ResizeElement = exports.Plugin = exports.EditBar = exports.ZoomWheel = exports.SelectHighlight = exports.SelectAll = exports.Interaction = exports.HotkeyManager = exports.HotkeyHistory = exports.DragElement = exports.DblClickEditText = exports.ClickSelect = exports.BrushSelect = exports.getThemeColors = exports.getItemProps = exports.VERSION = void 0;
exports.THEME_NAMES = exports.TEMPLATE_NAMES = exports.STRUCTURE_NAMES = exports.ITEM_NAMES = exports.getThemeDisplayName = exports.getTemplateDisplayName = exports.getStructureDisplayName = exports.getItemDisplayName = exports.parseSVG = exports.registerTheme = exports.getThemes = exports.getTheme = exports.registerTemplate = exports.getTemplates = exports.getTemplate = exports.parseSyntax = exports.Infographic = void 0;
const package_json_1 = __importDefault(require("../package.json"));
exports.VERSION = package_json_1.default.version;
__exportStar(require("./designs"), exports);
var utils_1 = require("./designs/utils");
Object.defineProperty(exports, "getItemProps", { enumerable: true, get: function () { return utils_1.getItemProps; } });
Object.defineProperty(exports, "getThemeColors", { enumerable: true, get: function () { return utils_1.getThemeColors; } });
var interactions_1 = require("./editor/interactions");
Object.defineProperty(exports, "BrushSelect", { enumerable: true, get: function () { return interactions_1.BrushSelect; } });
Object.defineProperty(exports, "ClickSelect", { enumerable: true, get: function () { return interactions_1.ClickSelect; } });
Object.defineProperty(exports, "DblClickEditText", { enumerable: true, get: function () { return interactions_1.DblClickEditText; } });
Object.defineProperty(exports, "DragElement", { enumerable: true, get: function () { return interactions_1.DragElement; } });
Object.defineProperty(exports, "HotkeyHistory", { enumerable: true, get: function () { return interactions_1.HotkeyHistory; } });
Object.defineProperty(exports, "HotkeyManager", { enumerable: true, get: function () { return interactions_1.HotkeyManager; } });
Object.defineProperty(exports, "Interaction", { enumerable: true, get: function () { return interactions_1.Interaction; } });
Object.defineProperty(exports, "SelectAll", { enumerable: true, get: function () { return interactions_1.SelectAll; } });
Object.defineProperty(exports, "SelectHighlight", { enumerable: true, get: function () { return interactions_1.SelectHighlight; } });
Object.defineProperty(exports, "ZoomWheel", { enumerable: true, get: function () { return interactions_1.ZoomWheel; } });
var plugins_1 = require("./editor/plugins");
Object.defineProperty(exports, "EditBar", { enumerable: true, get: function () { return plugins_1.EditBar; } });
Object.defineProperty(exports, "Plugin", { enumerable: true, get: function () { return plugins_1.Plugin; } });
Object.defineProperty(exports, "ResizeElement", { enumerable: true, get: function () { return plugins_1.ResizeElement; } });
var jsx_1 = require("./jsx");
Object.defineProperty(exports, "Defs", { enumerable: true, get: function () { return jsx_1.Defs; } });
Object.defineProperty(exports, "Ellipse", { enumerable: true, get: function () { return jsx_1.Ellipse; } });
Object.defineProperty(exports, "Fragment", { enumerable: true, get: function () { return jsx_1.Fragment; } });
Object.defineProperty(exports, "Group", { enumerable: true, get: function () { return jsx_1.Group; } });
Object.defineProperty(exports, "Path", { enumerable: true, get: function () { return jsx_1.Path; } });
Object.defineProperty(exports, "Polygon", { enumerable: true, get: function () { return jsx_1.Polygon; } });
Object.defineProperty(exports, "Rect", { enumerable: true, get: function () { return jsx_1.Rect; } });
Object.defineProperty(exports, "Text", { enumerable: true, get: function () { return jsx_1.Text; } });
Object.defineProperty(exports, "cloneElement", { enumerable: true, get: function () { return jsx_1.cloneElement; } });
Object.defineProperty(exports, "createFragment", { enumerable: true, get: function () { return jsx_1.createFragment; } });
Object.defineProperty(exports, "createLayout", { enumerable: true, get: function () { return jsx_1.createLayout; } });
Object.defineProperty(exports, "getCombinedBounds", { enumerable: true, get: function () { return jsx_1.getCombinedBounds; } });
Object.defineProperty(exports, "getElementBounds", { enumerable: true, get: function () { return jsx_1.getElementBounds; } });
Object.defineProperty(exports, "getElementsBounds", { enumerable: true, get: function () { return jsx_1.getElementsBounds; } });
Object.defineProperty(exports, "jsx", { enumerable: true, get: function () { return jsx_1.jsx; } });
Object.defineProperty(exports, "jsxDEV", { enumerable: true, get: function () { return jsx_1.jsxDEV; } });
Object.defineProperty(exports, "jsxs", { enumerable: true, get: function () { return jsx_1.jsxs; } });
Object.defineProperty(exports, "renderSVG", { enumerable: true, get: function () { return jsx_1.renderSVG; } });
var renderer_1 = require("./renderer");
Object.defineProperty(exports, "getFont", { enumerable: true, get: function () { return renderer_1.getFont; } });
Object.defineProperty(exports, "getFonts", { enumerable: true, get: function () { return renderer_1.getFonts; } });
Object.defineProperty(exports, "getPalette", { enumerable: true, get: function () { return renderer_1.getPalette; } });
Object.defineProperty(exports, "getPaletteColor", { enumerable: true, get: function () { return renderer_1.getPaletteColor; } });
Object.defineProperty(exports, "registerFont", { enumerable: true, get: function () { return renderer_1.registerFont; } });
Object.defineProperty(exports, "registerPalette", { enumerable: true, get: function () { return renderer_1.registerPalette; } });
Object.defineProperty(exports, "registerPattern", { enumerable: true, get: function () { return renderer_1.registerPattern; } });
Object.defineProperty(exports, "setDefaultFont", { enumerable: true, get: function () { return renderer_1.setDefaultFont; } });
var resource_1 = require("./resource");
Object.defineProperty(exports, "loadSVGResource", { enumerable: true, get: function () { return resource_1.loadSVGResource; } });
Object.defineProperty(exports, "registerResourceLoader", { enumerable: true, get: function () { return resource_1.registerResourceLoader; } });
var resource_2 = require("./resource");
Object.defineProperty(exports, "clearPreloadCache", { enumerable: true, get: function () { return resource_2.clearPreloadCache; } });
Object.defineProperty(exports, "getPreloadedResource", { enumerable: true, get: function () { return resource_2.getPreloadedResource; } });
Object.defineProperty(exports, "getPreloadStats", { enumerable: true, get: function () { return resource_2.getPreloadStats; } });
Object.defineProperty(exports, "isResourcePreloaded", { enumerable: true, get: function () { return resource_2.isResourcePreloaded; } });
Object.defineProperty(exports, "preloadResource", { enumerable: true, get: function () { return resource_2.preloadResource; } });
Object.defineProperty(exports, "preloadResources", { enumerable: true, get: function () { return resource_2.preloadResources; } });
var runtime_1 = require("./runtime");
Object.defineProperty(exports, "Infographic", { enumerable: true, get: function () { return runtime_1.Infographic; } });
var syntax_1 = require("./syntax");
Object.defineProperty(exports, "parseSyntax", { enumerable: true, get: function () { return syntax_1.parseSyntax; } });
var templates_1 = require("./templates");
Object.defineProperty(exports, "getTemplate", { enumerable: true, get: function () { return templates_1.getTemplate; } });
Object.defineProperty(exports, "getTemplates", { enumerable: true, get: function () { return templates_1.getTemplates; } });
Object.defineProperty(exports, "registerTemplate", { enumerable: true, get: function () { return templates_1.registerTemplate; } });
var themes_1 = require("./themes");
Object.defineProperty(exports, "getTheme", { enumerable: true, get: function () { return themes_1.getTheme; } });
Object.defineProperty(exports, "getThemes", { enumerable: true, get: function () { return themes_1.getThemes; } });
Object.defineProperty(exports, "registerTheme", { enumerable: true, get: function () { return themes_1.registerTheme; } });
var utils_2 = require("./utils");
Object.defineProperty(exports, "parseSVG", { enumerable: true, get: function () { return utils_2.parseSVG; } });
// i18n 翻译
var i18n_1 = require("./i18n");
Object.defineProperty(exports, "getItemDisplayName", { enumerable: true, get: function () { return i18n_1.getItemDisplayName; } });
Object.defineProperty(exports, "getStructureDisplayName", { enumerable: true, get: function () { return i18n_1.getStructureDisplayName; } });
Object.defineProperty(exports, "getTemplateDisplayName", { enumerable: true, get: function () { return i18n_1.getTemplateDisplayName; } });
Object.defineProperty(exports, "getThemeDisplayName", { enumerable: true, get: function () { return i18n_1.getThemeDisplayName; } });
Object.defineProperty(exports, "ITEM_NAMES", { enumerable: true, get: function () { return i18n_1.ITEM_NAMES; } });
Object.defineProperty(exports, "STRUCTURE_NAMES", { enumerable: true, get: function () { return i18n_1.STRUCTURE_NAMES; } });
Object.defineProperty(exports, "TEMPLATE_NAMES", { enumerable: true, get: function () { return i18n_1.TEMPLATE_NAMES; } });
Object.defineProperty(exports, "THEME_NAMES", { enumerable: true, get: function () { return i18n_1.THEME_NAMES; } });
