export const TEMPLATE_MAP: Record<string, string> = {
    // 列表类
    'list-row-horizontal-icon-arrow': '横向列表 · 图标箭头',
    'list-row-horizontal-icon-line': '横向列表 · 图标连线',
    'list-row-simple-horizontal-arrow': '横向列表 · 简约箭头',
    'list-row-simple-illus': '横向列表 · 插画风格',
    'list-row-circular-progress': '横向列表 · 环形进度',
    'list-column-done-list': '纵向列表 · 任务清单',
    'list-column-vertical-icon-arrow': '纵向列表 · 图标箭头',
    'list-column-simple-vertical-arrow': '纵向列表 · 简约箭头',
    'list-grid-badge-card': '网格布局 · 徽章卡片',
    'list-grid-candy-card-lite': '网格布局 · 糖果卡片',
    'list-grid-ribbon-card': '网格布局 · 丝带卡片',
    'list-grid-compact-card': '网格布局 · 紧凑卡片',
    'list-grid-progress-card': '网格布局 · 进度卡片',
    'list-grid-circular-progress': '网格布局 · 环形进度',
    'list-grid-done-list': '网格布局 · 任务清单',
    'list-grid-horizontal-icon-arrow': '网格布局 · 横向箭头',
    'list-grid-simple': '网格布局 · 简约风格',
    'list-pyramid-rounded-rect-node': '金字塔 · 圆角矩形',
    'list-pyramid-badge-card': '金字塔 · 徽章卡片',
    'list-pyramid-compact-card': '金字塔 · 紧凑卡片',
    'list-sector-simple': '扇形布局 · 简约风格',
    'list-sector-plain-text': '扇形布局 · 纯文本',
    'list-sector-half-plain-text': '半圆扇形布局',

    // 流程/步骤类
    'sequence-steps-simple': '步骤流程 · 简约风格',
    'sequence-steps-badge-card': '步骤流程 · 徽章卡片',
    'sequence-steps-simple-illus': '步骤流程 · 插画风格',
    'sequence-ascending-steps': '阶梯流程 · 上升台阶',
    'sequence-ascending-stairs-3d-simple': '3D阶梯 · 简约风格',
    'sequence-ascending-stairs-3d-underline-text': '3D阶梯 · 下划线文本',
    'sequence-snake-steps-simple': '蛇形流程 · 简约风格',
    'sequence-snake-steps-compact-card': '蛇形流程 · 紧凑卡片',
    'sequence-snake-steps-pill-badge': '蛇形流程 · 胶囊徽章',
    'sequence-snake-steps-simple-illus': '蛇形流程 · 插画风格',
    'sequence-snake-steps-underline-text': '蛇形流程 · 下划线文本',
    'sequence-color-snake-steps-horizontal-icon-line': '彩色蛇形 · 图标连线',
    'sequence-color-snake-steps-simple-illus': '彩色蛇形 · 插画风格',
    'sequence-zigzag-steps-underline-text': 'Z字流程 · 下划线文本',
    'sequence-horizontal-zigzag-simple': '水平Z字 · 简约风格',
    'sequence-horizontal-zigzag-underline-text': '水平Z字 · 下划线文本',
    'sequence-horizontal-zigzag-simple-illus': '水平Z字 · 插画风格',
    'sequence-horizontal-zigzag-horizontal-icon-line': '水平Z字 · 图标连线',
    'sequence-horizontal-zigzag-plain-text': '水平Z字 · 纯文本',
    'sequence-horizontal-zigzag-simple-horizontal-arrow': '水平Z字 · 简约箭头',
    'sequence-timeline-simple': '时间轴 · 简约风格',
    'sequence-timeline-plain-text': '时间轴 · 纯文本',
    'sequence-timeline-done-list': '时间轴 · 任务清单',
    'sequence-timeline-rounded-rect-node': '时间轴 · 圆角矩形',
    'sequence-timeline-simple-illus': '时间轴 · 插画风格',
    'sequence-roadmap-vertical-simple': '垂直路线图 · 简约风格',
    'sequence-roadmap-vertical-plain-text': '垂直路线图 · 纯文本',
    'sequence-roadmap-vertical-badge-card': '垂直路线图 · 徽章卡片',
    'sequence-roadmap-vertical-pill-badge': '垂直路线图 · 胶囊徽章',
    'sequence-roadmap-vertical-quarter-circular': '垂直路线图 · 四分圆',
    'sequence-roadmap-vertical-quarter-simple-card': '垂直路线图 · 简约卡片',
    'sequence-roadmap-vertical-underline-text': '垂直路线图 · 下划线文本',
    'sequence-circular-simple': '循环流程 · 简约风格',
    'sequence-circular-underline-text': '循环流程 · 下划线文本',
    'sequence-pyramid-simple': '金字塔流程',
    'sequence-cylinders-3d-simple': '3D圆柱流程',
    'sequence-zigzag-pucks-3d-simple': '3D圆盘Z字流程',
    'sequence-zigzag-pucks-3d-underline-text': '3D圆盘Z字 · 下划线',
    'sequence-zigzag-pucks-3d-indexed-card': '3D圆盘Z字 · 索引卡片',
    'sequence-circle-arrows-indexed-card': '循环箭头 · 索引卡片',
    'sequence-filter-mesh-simple': '漏斗图 · 简约风格',
    'sequence-filter-mesh-underline-text': '漏斗图 · 下划线文本',
    'sequence-mountain-underline-text': '山峰流程 · 下划线文本',
    'sequence-mountain-simple': '山峰流程 · 简约风格',
    'sequence-stairs-front-pill-badge': '正面阶梯 · 胶囊徽章',
    'sequence-stairs-front-compact-card': '正面阶梯 · 紧凑卡片',
    'sequence-stairs-front-simple': '正面阶梯 · 简约风格',
    'sequence-stairs-side-pill-badge': '侧面阶梯 · 胶囊徽章',
    'sequence-stairs-side-compact-card': '侧面阶梯 · 紧凑卡片',
    'sequence-stairs-side-simple': '侧面阶梯 · 简约风格',

    // 对比类
    'compare-swot': 'SWOT 分析',
    'compare-binary-horizontal-simple-vs': 'VS对比 · 简约风格',
    'compare-binary-horizontal-underline-text-vs': 'VS对比 · 下划线文本',
    'compare-binary-horizontal-badge-card-vs': 'VS对比 · 徽章卡片',
    'compare-binary-horizontal-compact-card-vs': 'VS对比 · 紧凑卡片',
    'compare-binary-horizontal-simple-fold': '折叠对比 · 简约风格',
    'compare-binary-horizontal-underline-text-fold': '折叠对比 · 下划线文本',
    'compare-binary-horizontal-badge-card-fold': '折叠对比 · 徽章卡片',
    'compare-binary-horizontal-compact-card-fold': '折叠对比 · 紧凑卡片',
    'compare-binary-horizontal-simple-arrow': '箭头对比 · 简约风格',
    'compare-binary-horizontal-underline-text-arrow': '箭头对比 · 下划线文本',
    'compare-binary-horizontal-badge-card-arrow': '箭头对比 · 徽章卡片',
    'compare-binary-horizontal-compact-card-arrow': '箭头对比 · 紧凑卡片',
    'compare-hierarchy-left-right-circle-node-pill-badge': '左右层级对比 · 胶囊徽章',
    'compare-hierarchy-left-right-circle-node-plain-text': '左右层级对比 · 纯文本',
    'compare-hierarchy-row-letter-card-compact-card': '行层级对比 · 字母卡片',
    'compare-hierarchy-row-letter-card-rounded-rect-node': '行层级对比 · 圆角矩形',

    // 图表类
    'chart-column-simple': '柱状图',
    'chart-bar-plain-text': '条形图',
    'chart-line-plain-text': '折线图',
    'chart-pie-plain-text': '饼图 · 纯文本',
    'chart-pie-compact-card': '饼图 · 紧凑卡片',
    'chart-pie-pill-badge': '饼图 · 胶囊徽章',
    'chart-pie-donut-plain-text': '环形图 · 纯文本',
    'chart-pie-donut-compact-card': '环形图 · 紧凑卡片',
    'chart-pie-donut-pill-badge': '环形图 · 胶囊徽章',
    'chart-wordcloud': '词云图',
    'chart-wordcloud-rotate': '词云图 · 旋转',

    // 其他
    'quadrant-quarter-simple-card': '四象限 · 简约卡片',
    'quadrant-quarter-circular': '四象限 · 圆形风格',
    'quadrant-simple-illus': '四象限 · 插画风格',
    'relation-circle-icon-badge': '圆形关系图 · 图标徽章',
    'relation-circle-circular-progress': '圆形关系图 · 环形进度',

    // 层级树类
    'hierarchy-tree-tech-style-capsule-item': '层级树 · 科技风胶囊',
    'hierarchy-tree-tech-style-rounded-rect-node': '层级树 · 科技风圆角',
    'hierarchy-tree-tech-style-compact-card': '层级树 · 科技风紧凑',
    'hierarchy-tree-tech-style-badge-card': '层级树 · 科技风徽章',
    'hierarchy-tree-tech-style-ribbon-card': '层级树 · 科技风丝带',
    'hierarchy-tree-dashed-line-capsule-item': '层级树 · 虚线胶囊',
    'hierarchy-tree-dashed-line-rounded-rect-node': '层级树 · 虚线圆角',
    'hierarchy-tree-dashed-line-compact-card': '层级树 · 虚线紧凑',
    'hierarchy-tree-dashed-line-badge-card': '层级树 · 虚线徽章',
    'hierarchy-tree-dashed-line-ribbon-card': '层级树 · 虚线丝带',
    'hierarchy-tree-distributed-origin-capsule-item': '层级树 · 分布式胶囊',
    'hierarchy-tree-distributed-origin-rounded-rect-node': '层级树 · 分布式圆角',
    'hierarchy-tree-distributed-origin-compact-card': '层级树 · 分布式紧凑',
    'hierarchy-tree-distributed-origin-badge-card': '层级树 · 分布式徽章',
    'hierarchy-tree-distributed-origin-ribbon-card': '层级树 · 分布式丝带',
    'hierarchy-tree-curved-line-capsule-item': '层级树 · 曲线胶囊',
    'hierarchy-tree-curved-line-rounded-rect-node': '层级树 · 曲线圆角',
    'hierarchy-tree-curved-line-compact-card': '层级树 · 曲线紧凑',
    'hierarchy-tree-curved-line-badge-card': '层级树 · 曲线徽章',
    'hierarchy-tree-curved-line-ribbon-card': '层级树 · 曲线丝带',
    'hierarchy-tree-dashed-arrow-capsule-item': '层级树 · 虚线箭头胶囊',
    'hierarchy-tree-dashed-arrow-rounded-rect-node': '层级树 · 虚线箭头圆角',
    'hierarchy-tree-dashed-arrow-compact-card': '层级树 · 虚线箭头紧凑',
    'hierarchy-tree-dashed-arrow-badge-card': '层级树 · 虚线箭头徽章',
    'hierarchy-tree-dashed-arrow-ribbon-card': '层级树 · 虚线箭头丝带',

    // 思维导图类
    'hierarchy-mindmap-branch-gradient-lined-palette': '思维导图 · 分支渐变线条',
    'hierarchy-mindmap-level-gradient-lined-palette': '思维导图 · 层级渐变线条',
    'hierarchy-mindmap-branch-gradient-capsule-item': '思维导图 · 分支渐变胶囊',
    'hierarchy-mindmap-level-gradient-capsule-item': '思维导图 · 层级渐变胶囊',
    'hierarchy-mindmap-branch-gradient-circle-progress': '思维导图 · 分支渐变环形',
    'hierarchy-mindmap-level-gradient-circle-progress': '思维导图 · 层级渐变环形',
    'hierarchy-mindmap-branch-gradient-rounded-rect': '思维导图 · 分支渐变圆角',
    'hierarchy-mindmap-level-gradient-rounded-rect': '思维导图 · 层级渐变圆角',
    'hierarchy-mindmap-branch-gradient-compact-card': '思维导图 · 分支渐变紧凑',
    'hierarchy-mindmap-level-gradient-compact-card': '思维导图 · 层级渐变紧凑',
    'hierarchy-mindmap-branch-gradient-circle-node': '思维导图 · 分支渐变圆形',
    'hierarchy-mindmap-level-gradient-circle-node': '思维导图 · 层级渐变圆形',
    'hierarchy-mindmap-branch-gradient-rounded-rect-node': '思维导图 · 分支渐变圆角节点',
    'hierarchy-mindmap-level-gradient-rounded-rect-node': '思维导图 · 层级渐变圆角节点',
};

export const TEMPLATE_CATEGORIES = [
    {
        name: '列表类',
        key: 'list',
        templates: [
            'list-row-horizontal-icon-arrow', 'list-row-horizontal-icon-line',
            'list-row-simple-horizontal-arrow', 'list-row-simple-illus',
            'list-grid-badge-card', 'list-grid-candy-card-lite',
            'list-grid-ribbon-card', 'list-sector-plain-text'
        ]
    },
    {
        name: '流程/时序类',
        key: 'sequence',
        templates: [
            'sequence-timeline-simple', 'sequence-timeline-rounded-rect-node',
            'sequence-roadmap-vertical-simple', 'sequence-ascending-steps',
            'sequence-snake-steps-simple', 'sequence-zigzag-steps-underline-text',
            'sequence-circular-simple', 'sequence-pyramid-simple'
        ]
    },
    {
        name: '对比分析类',
        key: 'compare',
        templates: [
            'compare-swot', 'compare-binary-horizontal-simple-fold',
            'compare-binary-horizontal-badge-card-arrow', 'compare-binary-horizontal-underline-text-vs',
            'compare-hierarchy-left-right-circle-node-pill-badge'
        ]
    },
    {
        name: '图表类',
        key: 'chart',
        templates: [
            'chart-column-simple', 'chart-bar-plain-text',
            'chart-line-plain-text', 'chart-pie-plain-text',
            'chart-pie-compact-card', 'chart-wordcloud'
        ]
    }
];

export const getTemplateName = (key: string) => TEMPLATE_MAP[key] || key;
